<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="15.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GymMangementDAL\GymMangementDAL.csproj" />
	</ItemGroup>

	<ItemGroup>
		<!-- Not recommended as first choice for web types, but can be used for minimal hosting-only needs -->
		<PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
	</ItemGroup>

	<ItemGroup>
		<!-- Make ASP.NET Core web types (including IWebHostEnvironment) available to this class library -->
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>

